let wordList = [
    "absence", "abolish", "absorb", "abundant", "accent",
    "accessible", "accumulation", "achievement", "acid", "acquaintance",
    "acquit", "activity", "addicted", "admire", "adult", "adventure",
    "advertise", "advertising", "adviser", "advocate", "affect", "alarm",
    "alive", "allocation", "allowance", "ambition", "anger", "angle",
    "animal", "anniversary", "anxiety", "apathy", "apology", "appearance",
    "applaud", "appoint", "appointment", "approval", "area", "arena",
    "army", "arrange", "arrow", "articulate", "artist", "ask", "assault",
    "assessment", "at", "atmosphere", "attack", "attention", "attract",
    "audience", "autonomy", "average", "aware", "back", "background",
    "bad", "bald", "bang", "banish", "banner", "banquet", "bark",
    "barrier", "basic", "basin", "basketball", "battery", "battle", "bean",
    "bear", "beautiful", "bee", "behead", "bell", "belly", "belong",
    "belt", "beneficiary", "bike", "bind", "bingo", "bird", "blackmail",
    "bland", "blank", "bloodshed", "blow", "blue", "bomber", "border",
    "bottom", "brag", "brain", "brave", "bread", "break", "breakdown",
    "breast", "breed", "breeze", "bridge", "bring", "brother", "bubble",
    "bucket", "building", "bullet", "bulletin", "burn", "burst", "bury",
    "business", "button", "by", "calculation", "calf", "call", "calorie",
    "camp", "cancel", "captain", "car", "care", "carriage", "cart", "cash",
    "cassette", "castle", "casualty", "cat", "cathedral", "cell",
    "cemetery", "censorship", "census", "central", "chain", "challenge",
    "charge", "charismatic", "cherry", "chest", "child", "choice", "chord",
    "chorus", "citizen", "civilization", "claim", "clash", "class", "clay",
    "clean", "clear", "clique", "close", "clothes", "cluster", "coalition",
    "coat", "coerce", "coffee", "coincidence", "cold", "collar", "collect",
    "colon", "colony", "color", "color", "colorful", "column",
    "combination", "comfort", "command", "comment", "committee", "common",
    "compact", "company", "compartment", "compensation", "compete",
    "competition", "complain", "complex", "comprehensive", "computer",
    "computing", "conception", "conclusion", "confidence", "confuse",
    "congress", "consciousness", "conservation", "conservative",
    "consideration", "consolidate", "conspiracy", "constitution",
    "consultation", "contemporary", "context", "contract", "contraction",
    "contradiction", "contrary", "conventional", "cooperation", "cope",
    "corn", "corner", "corpse", "correction", "costume", "cottage",
    "cotton", "counter", "country", "couple", "court", "cream", "create",
    "creation", "credibility", "creep", "criticism", "crop", "crossing",
    "crosswalk", "crown", "crusade", "crystal", "cupboard", "curtain",
    "cut", "dairy", "dance", "dash", "dead", "deadly", "decide", "deck",
    "decorative", "defend", "deficiency", "definite", "definition",
    "degree", "delete", "demand", "denial", "density", "dentist", "depart",
    "depend", "deprivation", "describe", "desert", "destruction",
    "detective", "deteriorate", "determine", "development", "devote",
    "dialogue", "die", "dignity", "dimension", "diplomat", "diplomatic",
    "disability", "disappear", "disappointment", "disaster", "discipline",
    "disco", "discourage", "discreet", "discuss", "disgrace", "disk",
    "dismissal", "disorder", "displace", "disposition", "distort",
    "district", "disturbance", "dive", "division", "document", "dog",
    "dollar", "dominant", "domination", "double", "dough", "dozen",
    "drama", "drawing", "dressing", "dribble", "drift", "drown", "duke",
    "dump", "duty", "earthquake", "eat", "eavesdrop", "echo", "economics",
    "economy", "ecstasy", "effect", "efflux", "eject", "elaborate",
    "elbow", "electronics", "element", "elite", "embark", "embox",
    "embryo", "emotion", "emphasis", "empire", "employ", "endure", "enemy",
    "engine", "ensure", "entitlement", "environment", "environmental",
    "epicalyx", "equal", "equip", "era", "escape", "essential",
    "establish", "ethics", "evolution", "ex", "examination", "excess",
    "exclude", "exclusive", "executrix", "exempt", "exemption",
    "expansion", "expectation", "experiment", "explain", "expose",
    "expression", "extend", "extension", "fabricate", "facade", "fade",
    "faint", "faith", "fantasy", "fashionable", "favor", "fax", "feast",
    "federation", "feel", "feeling", "feminist", "ferry", "few", "fibre",
    "fiction", "field", "fill", "film", "filter", "finance", "finish",
    "finished", "firefighter", "first", "fit", "fitness", "flag", "flat",
    "flavor", "flock", "flush", "fog", "forest", "formation", "formula",
    "formulate", "foster", "foundation", "fountain", "fragrant", "frame",
    "frank", "friendly", "frighten", "front", "full", "fund", "fur",
    "future", "game", "garage", "garbage", "gem", "giant", "girl",
    "girlfriend", "give", "glass", "global", "gloom", "go", "goalkeeper",
    "gold", "good", "government", "gradient", "gravel", "graze",
    "gregarious", "grind", "ground", "guideline", "guilt", "guitar", "gun",
    "habitat", "hall", "hallway", "halt", "hammer", "handy", "harass",
    "harmony", "harsh", "harvest", "haunt", "have", "headline",
    "headquarters", "heal", "heel", "helmet", "herd", "hierarchy", "hike",
    "hill", "hip", "history", "home", "homosexual", "honor", "horoscope",
    "horror", "hostility", "hour", "house", "hover", "hurl", "husband",
    "ice", "ideology", "ignorant", "image", "impact", "imposter",
    "impress", "improve", "incapable", "incident", "incongruous",
    "increase", "indirect", "indoor", "indulge", "infinite", "inflation",
    "infrastructure", "inn", "innocent", "inspector", "insure",
    "integrated", "integration", "integrity", "intelligence", "interest",
    "intermediate", "intervention", "invite", "iron", "is", "island",
    "issue", "item", "ivory", "jet", "job", "journal", "jump", "junior",
    "jurisdiction", "justify", "kid", "kneel", "knock", "know",
    "knowledge", "lace", "lamb", "lamp", "landowner", "lane", "last",
    "late", "lay", "lean", "left", "leftovers", "legend", "letter",
    "liability", "lick", "lifestyle", "like", "lily", "lion", "list",
    "literacy", "literature", "live", "loan", "lobby", "log", "lonely",
    "lost", "love", "machinery", "magnetic", "mail", "majority", "manage",
    "manual", "march", "mark", "marketing", "marsh", "mass", "meal",
    "meaning", "medal", "memorial", "memory", "method", "midnight", "mild",
    "mile", "miner", "minority", "mix", "mixture", "module", "money",
    "monster", "month", "mosaic", "motif", "motivation", "motorcycle",
    "mourning", "mouth", "movement", "movie", "muggy", "mutual", "my",
    "name", "nap", "neck", "need", "negative", "negligence", "neighbour",
    "nerve", "net", "network", "news", "no", "nomination", "nonremittal",
    "nose", "novel", "nuance", "nun", "nut", "object", "objective",
    "obligation", "obscure", "observer", "occupy", "offend", "offensive",
    "offset", "offspring", "old", "onion", "open", "operation",
    "operational", "oppose", "opposition", "orange", "orbit", "ordinary",
    "organ", "organisation", "orgy", "origin", "outlet", "outlook",
    "overlook", "packet", "paint", "palm", "panel", "paper", "parachute",
    "paralyzed", "parameter", "part", "passion", "password", "pasture",
    "path", "patience", "pattern", "peak", "penalty", "penetrate",
    "pepper", "perceive", "performer", "persist", "pest", "petty",
    "philosophy", "photograph", "pick", "pipe", "platform", "player",
    "please", "pleasure", "pledge", "plot", "pluck", "plug", "poetry",
    "polish", "popular", "positive", "post", "potential", "pottery",
    "practical", "practice", "preach", "precision", "prescription",
    "presence", "presentation", "presidency", "prestige", "prevalence",
    "primary", "priority", "private", "product", "program", "proper",
    "proposal", "prosecution", "prosper", "proud", "prove", "provoke",
    "psychology", "publication", "publisher", "pudding", "put", "qualify",
    "quality", "quantity", "quotation", "quote", "racism", "radio",
    "railcar", "rainbow", "rally", "ranch", "random", "range", "ratio",
    "reach", "reaction", "reader", "ready", "realism", "reasonable",
    "rebel", "recession", "reckless", "recommend", "reconcile", "record",
    "recover", "recovery", "recruit", "recycle", "red", "redeem",
    "redundancy", "reflection", "regard", "regret", "reject", "related",
    "relax", "release", "relieve", "remain", "remark", "remind",
    "repetition", "report", "represent", "reptile", "reputation",
    "requirement", "resort", "responsible", "restless", "restoration",
    "restrain", "restrict", "result", "retired", "retirement", "retreat",
    "review", "ribbon", "rice", "ride", "rifle", "riot", "road", "rob",
    "robot", "room", "rotation", "rough", "row", "rub", "rubbish", "rugby",
    "rumor", "run", "sale", "salmon", "salt", "sand", "sandwich",
    "satisfied", "sausage", "scale", "scatter", "science", "score",
    "scramble", "scrap", "screw", "seal", "seat", "section", "sector",
    "see", "seek", "self", "seller", "sensation", "sequence", "sermon",
    "service", "session", "settle", "shame", "share", "shatter", "shift",
    "shortage", "shrink", "sickness", "side", "silence", "similar",
    "simplicity", "sin", "sip", "sister", "skate", "slam", "slap", "slide",
    "slip", "slump", "smash", "smile", "snap", "snarl", "snub", "so",
    "socialist", "society", "soft", "solo", "solve", "soul", "sound",
    "speech", "spine", "split", "spray", "spread", "spring", "spy",
    "stake", "station", "steak", "steep", "step", "stereotype", "sticky",
    "sting", "straighten", "straw", "stream", "strikebreaker", "string",
    "struggle", "student", "style", "subject", "substitute", "subway",
    "suffering", "suite", "summer", "summit", "superior", "sweater",
    "sweep", "switch", "symbol", "sympathetic", "tablet", "tactic", "take",
    "talented", "talk", "tank", "taste", "tasty", "tax", "taxi", "team",
    "tear", "teenager", "television", "temporary", "tendency", "terrify",
    "text", "thank", "theme", "theory", "thin", "think", "thinker",
    "thirsty", "thoughtful", "threat", "threshold", "throne", "tiger",
    "timetable", "tin", "tip", "tolerate", "tool", "topple", "touch",
    "tough", "tourist", "tower", "traction", "trade", "traffic", "trait",
    "transfer", "transform", "transition", "transparent", "treatment",
    "treaty", "trend", "tribe", "trouble", "tube", "tumour", "turkey",
    "twist", "twitch", "unaware", "uncle", "underline", "undermine",
    "understanding", "undertake", "undress", "union", "unlike", "unlikely",
    "unpleasant", "urine", "us", "use", "user", "utter", "vacuum", "valid",
    "variety", "vat", "vegetable", "veil", "version", "vertical", "view",
    "violation", "virus", "visible", "waist", "wait", "wall", "wander",
    "want", "ward", "warm", "watch", "waterfall", "wave", "wealth",
    "wedding", "wheel", "whip", "whole", "wild", "wilderness", "win",
    "wolf", "wood", "word", "world", "worm", "wrist", "writer", "wrong",
    "youth", "zone"
]

export function getRandomWord() {
  return wordList[Math.floor(Math.random() * wordList.length)];
}
